import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elbin Binil",
  description: "Generated by create next app",
  openGraph: {
    title: "Elbin Binil",
    type: "article",
    url: "https://elbinbinil.github.io/",
    images: [
      {
        url: "https://media.licdn.com/dms/image/D5635AQGc1w2vmm3qHQ/profile-framedphoto-shrink_400_400/0/1687782663007?e=1722067200&v=beta&t=CJeDzwRj5uFRWZ26cQDg3R3s4u_em_6Dg-4yLdYfX8U",
        width: 400,
        height: 400,
        alt: "Profile image",
      },
    ],
    description:
      "This website is all about me and my Youtube channel. I would share all sorts of tech news and tech updates for you.",
  },
  twitter: {
    card: "summary",
    site: "@elbinbinil",
    title: "Elbin Binil",
    description:
      "This website is all about me and my Youtube channel. I would share all sorts of tech news and tech updates for you.",
    images:
      "https://media.licdn.com/dms/image/D5635AQGc1w2vmm3qHQ/profile-framedphoto-shrink_400_400/0/1687782663007?e=1722067200&v=beta&t=CJeDzwRj5uFRWZ26cQDg3R3s4u_em_6Dg-4yLdYfX8U",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
